# ref: https://hub.docker.com/r/itzg/minecraft-server/
image: itzg/minecraft-server
imageTag: latest

minecraft:
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  minecraftServer:
    eula: true
    type: paper
    version: latest
    difficulty: peaceful
    # A comma-separated list of player names who should be admins.
    ops: k014
    # A server icon URL for server listings. Auto-scaled and transcoded.
    icon:
    # Define this if you want a specific map generation seed.
    levelSeed:
    # Message of the Day
    motd: "k014's Minecraft Server!"
    # Check accounts against Minecraft account service.
    onlineMode: true
    # If you adjust this, you may need to adjust resources.requests above to match.
    memory: 1024M
    serviceType: NodePort
    loadBalancerIP:

    rcon:
      # If you enable this, make SURE to change your password below.
      enabled: false
      port: 25575
      password: "CHANGEME!"
      serviceType: NodePort
      loadBalancerIP:
      # loadBalancerSourceRanges: []
      ## Set the externalTrafficPolicy in the Service to either Cluster or Local
      # externalTrafficPolicy: Cluster

    query:
      # If you enable this, your server will be "published" to Gamespy
      enabled: false
      port: 25565

  persistence:
    storageClass: manual
    dataDir:
      enabled: true
      Size: 1Gi
