apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    namespace: default
    name: mc-minecraft-datadir
  gcePersistentDisk:
    pdName: mc-disk-2
    fsType: ext4
